-
  name: "Example project"
  notification: slack
  logo: images/logos/example.png
  members:
    - UEMA8DE9Y
    - UEN897F5U
-
  name: "Bar"
  notification: email
  logo: images/logos/bar.png
  members:
    - bar@example.com
-
  name: "Inactive project"
  notification: email
  logo: images/logos/example.png
  members:
    - inactive@example.com
  is_active: false
